settings:
  pattern-time: "dd-MM-yyyy HH:mm:ss"
  tg:
    chat-id:
      - ""
    token: ""
    enable: false

messages:
  no-permission: "&cУ вас нет прав на использование команды"
  player-not-found: "&cИгрок не найден"
  donate-not-found: "&cДонат не был найден в config.yml"
  command-not-found: "&cПодкоманда не найдена."
  success-reload: "&aУспешно перезагрузил конфиг"
  no-args-player: "&cВы не указали игрока"
  no-args-donate: "&cВы не указали донат"
  help:
    - ""
    - "&eПравильное использование команды:"
    - "&a/buyer give <ник> <донат> - Выдача привилегии"
    - "&a/buyer reload - Перезагрузить конфиг"
    - ""
groups:
  hero:
    give:
      - "lp user %player% parent add %group%"
    broadcast:
      - "Игрок %player% купил донат за 5 рублей"
    tg-message:
      - ""
      - "⚠️ Радуйтесь, только что на вашем сервере был куплен донат..."
      - ""
      - "Игрок: %player%"
      - "Купил: HERO (%date%)"
      - ""
      - "💸 Баланс пополнен на: 100p"

